// Generated by CoffeeScript 1.9.3
var expect, result;

expect = require('chai').expect;

result = require('../tasks/task-1')();

describe('Sample exam tests', function() {
  return describe('Players', function() {
    return describe('With valid input', function() {
      it('expect getPlayer to exist, to be a function and to take a single parameter', function() {
        expect(result.getPlayer).to.exist;
        expect(result.getPlayer).to.be.a('function');
        return expect(result.getPlayer).to.have.length(1);
      });
      it('expect getPlayer to return a new player instance, with provided name and generated id', function() {
        var name, player;
        name = 'Rock and roll';
        player = result.getPlayer(name);
        expect(player).to.exist;
        expect(player).to.be.an('object');
        expect(player.name).to.equal(name);
        return expect(player.id).to.exist;
      });
      return it('expect player.addPlaylist() to exists, to be a function and to take a single parameter', function() {
        var name, player;
        name = 'Rock and roll';
        player = result.getPlayer(name);
        expect(player.addPlaylist).to.exist;
        expect(player.addPlaylist).to.be.a('function');
        return expect(player.addPlaylist).to.have.length(1);
      });
    });
  });
});

//# sourceMappingURL=task-1-tests.js.map
